export default function TermsPage() {
  return (
    <div className="py-12">
      <div className="container-custom">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold text-gray-900 mb-6">Terms of Service</h1>
          <p className="text-gray-600 mb-8">Last updated: January 2026</p>

          <div className="prose prose-lg prose-rose">
            <div className="card mb-6">
              <h2 className="text-xl font-bold text-gray-900 mb-3">Acceptance of Terms</h2>
              <p className="text-gray-600">
                By accessing and using CSS Gradient Generator, you accept and agree to be bound 
                by these Terms of Service. If you do not agree to these terms, please do not use 
                our service.
              </p>
            </div>

            <div className="card mb-6">
              <h2 className="text-xl font-bold text-gray-900 mb-3">Use of Service</h2>
              <p className="text-gray-600 mb-4">
                CSS Gradient Generator is a free online tool for creating CSS gradients. You may use 
                this service for:
              </p>
              <ul className="space-y-2 text-gray-600">
                <li>• Personal projects</li>
                <li>• Commercial projects</li>
                <li>• Educational purposes</li>
                <li>• Any lawful purpose</li>
              </ul>
            </div>

            <div className="card mb-6">
              <h2 className="text-xl font-bold text-gray-900 mb-3">Generated Content</h2>
              <p className="text-gray-600">
                The CSS code generated by our tool is free to use without attribution. You own 
                full rights to any gradients you create using our service.
              </p>
            </div>

            <div className="card mb-6">
              <h2 className="text-xl font-bold text-gray-900 mb-3">Disclaimer</h2>
              <p className="text-gray-600">
                This service is provided &quot;as is&quot; without warranties of any kind. We do not 
                guarantee that the service will be uninterrupted, secure, or error-free. Use 
                at your own risk.
              </p>
            </div>

            <div className="card mb-6">
              <h2 className="text-xl font-bold text-gray-900 mb-3">Limitation of Liability</h2>
              <p className="text-gray-600">
                We shall not be liable for any indirect, incidental, special, consequential, or 
                punitive damages resulting from your use of or inability to use the service.
              </p>
            </div>

            <div className="card">
              <h2 className="text-xl font-bold text-gray-900 mb-3">Changes to Terms</h2>
              <p className="text-gray-600">
                We reserve the right to modify these terms at any time. Continued use of the 
                service after changes constitutes acceptance of the new terms.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
