'use client';

import { useState } from 'react';
import { ChevronDown } from 'lucide-react';

const faqs = [
  {
    question: 'What is a CSS gradient?',
    answer: 'A CSS gradient is a smooth transition between two or more colors. CSS supports two types of gradients: linear gradients (which go in a straight line) and radial gradients (which radiate from a center point). Gradients are commonly used for backgrounds, buttons, and other UI elements.',
  },
  {
    question: 'How do I use the generated CSS code?',
    answer: 'Simply click the "Copy" button to copy the CSS code to your clipboard. Then paste it into your CSS file or style tag. The code will look like: background: linear-gradient(90deg, #color1 0%, #color2 100%);',
  },
  {
    question: 'What is the difference between linear and radial gradients?',
    answer: 'Linear gradients transition colors along a straight line (you can control the angle). Radial gradients transition colors from a center point outward in a circular or elliptical pattern.',
  },
  {
    question: 'How many color stops can I add?',
    answer: 'Our tool supports up to 5 color stops. Each color stop has a color value and a position (0-100%). You need at least 2 color stops to create a gradient.',
  },
  {
    question: 'What does the angle control do?',
    answer: 'The angle control (available for linear gradients) determines the direction of the gradient. 0° goes from bottom to top, 90° goes from left to right, 180° goes from top to bottom, and 270° goes from right to left.',
  },
  {
    question: 'Is my gradient history saved?',
    answer: 'Yes! Your recent gradients are automatically saved to your browser\'s local storage. You can click on any saved gradient to load it back into the editor. This data stays on your device and is not sent to any server.',
  },
  {
    question: 'Can I use these gradients commercially?',
    answer: 'Absolutely! The CSS code generated by our tool is free to use for any purpose, including commercial projects. No attribution required.',
  },
  {
    question: 'Does this tool work on mobile devices?',
    answer: 'Yes, our gradient generator is fully responsive and works on smartphones, tablets, and desktop computers.',
  },
];

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <div className="py-12">
      <div className="container-custom">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">Frequently Asked Questions</h1>
          <p className="text-xl text-gray-600 mb-12">
            Find answers to common questions about our CSS Gradient Generator.
          </p>

          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={index} className="card overflow-hidden">
                <button
                  onClick={() => setOpenIndex(openIndex === index ? null : index)}
                  className="w-full flex items-center justify-between text-left p-6 hover:bg-rose-50/50 transition-colors"
                >
                  <span className="font-semibold text-gray-900 pr-4">{faq.question}</span>
                  <ChevronDown
                    className={`w-5 h-5 text-rose-600 flex-shrink-0 transition-transform duration-200 ${
                      openIndex === index ? 'rotate-180' : ''
                    }`}
                  />
                </button>
                {openIndex === index && (
                  <div className="px-6 pb-6">
                    <p className="text-gray-600 leading-relaxed">{faq.answer}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
